#remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/leap-day@v0.2.0
#remote_theme: pages-themes/modernist@v0.2.0
#remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/tactile@v0.2.0
#remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme

baseurl: "/js-level1-ja-docs"
url: "https://codeofgenius.github.io"

title: JavaScriptレベル1
description: JavaScriptレベル1　基礎文法1
author: Code of Genius

sass:
  sass_dir: assets/_sass
  style: compressed

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
